nginx:
  image: ttdev.fidelize.com.br:5000/nginx
  container_name: nginx-Gql
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./docker/nginx_conf:/etc/nginx/conf.d
  volumes_from:
   - php:rw
  links:
   - php

php:
  image: ttdev.fidelize.com.br:5000/php:7.1
  container_name: php-Gql
  restart: always 
  command: bash -c "sed -i \"s/memory_limit = 128M/memory_limit = 512M/\" /usr/local/etc/php/php.ini && sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini && sed -i \"s/max_execution_time = 30/max_execution_time = 300/\" /usr/local/etc/php/php.ini && php-fpm"
  environment:
   - XDEBUG_CONFIG=remote_host=172.17.0.1
  volumes:
   - ./:/var/www/html
   -  /usr/bin/ssh:/usr/bin/ssh

